name: dart validation

on:
  pull_request: 
  push:
    branches: [ main ] 

env:
  FLUTTER_VERSION: '3.41.1'

jobs:
  validation:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true 

      - name: Install Dependencies
        run: flutter pub get

      - name: Check Formatting
        run: dart format --set-exit-if-changed . 

      - name: Run Analysis
        uses: invertase/github-action-dart-analyzer@main
        with:
          fatal-infos: true 